# Generated by Django 4.2.23 on 2026-08-31 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_databasebackuplog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0007_document_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('kind', models.CharField(choices=[('excel', 'Excel/CSV'), ('bulk_cv', 'Nhiều CV')], default='excel', max_length=20)),
                ('source_label', models.CharField(blank=True, default='', help_text='Nguồn thu nhận gán cho cả lô; từng dòng có thể ghi đè bằng cột Nguồn.', max_length=40)),
                ('original_filename', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Nháp — chờ xác nhận'), ('committing', 'Đang ghi'), ('done', 'Đã ghi'), ('failed', 'Ghi lỗi')], db_index=True, default='draft', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('committed_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lô nhập liệu',
                'verbose_name_plural': 'Lô nhập liệu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Ô gốc đọc từ tệp, chưa chuẩn hoá')),
                ('fields', models.JSONField(blank=True, default=dict, help_text='Trường nghiệp vụ đã chuẩn hoá — phần lõi của SourceRecord.payload')),
                ('entity_key', models.CharField(blank=True, default='', max_length=300)),
                ('validation_status', models.CharField(choices=[('valid', 'Hợp lệ'), ('duplicate', 'Trùng — đã có trong hệ thống'), ('invalid', 'Lỗi dữ liệu'), ('skipped', 'Bỏ qua'), ('committed', 'Đã ghi'), ('error', 'Ghi thất bại')], db_index=True, default='invalid', max_length=20)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('cv_filename', models.CharField(blank=True, default='', max_length=300)),
                ('cv_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('cv_tmp_path', models.CharField(blank=True, default='', help_text='Đường dẫn file tạm tới khi commit', max_length=500)),
                ('ai_extracted', models.BooleanField(default=False, help_text='Trường do AI bóc từ CV, không phải người gõ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='intake.importbatch')),
                ('matched_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.person')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sourcerecord')),
            ],
            options={
                'verbose_name': 'Dòng nhập liệu',
                'verbose_name_plural': 'Dòng nhập liệu',
                'ordering': ['batch', 'row_number', 'pk'],
                'indexes': [models.Index(fields=['batch', 'validation_status'], name='intake_impo_batch_i_e632e9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['status', '-created_at'], name='intake_impo_status_6a9a55_idx'),
        ),
    ]
