# Generated by Django 4.2.23 on 2026-09-15 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('category', models.CharField(choices=[('hr_policy', 'Chính sách nhân sự'), ('recruitment_process', 'Quy trình tuyển dụng'), ('leadership_decision', 'Quyết định lãnh đạo'), ('guideline', 'Hướng dẫn nội bộ'), ('other', 'Khác')], db_index=True, default='other', max_length=40, verbose_name='Danh mục')),
                ('filename', models.CharField(blank=True, default='', max_length=300)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', help_text='Khử trùng lặp: cùng một file', max_length=64)),
                ('storage_key', models.CharField(blank=True, default='', help_text='Khoá trong kho file; trống = chỉ có văn bản nhập tay', max_length=500)),
                ('parsed_text', models.TextField(blank=True, default='', help_text='Văn bản Radar sẽ đọc. Nhập tay, hoặc dán lại nội dung trích từ file.', verbose_name='Nội dung')),
                ('parse_status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('done', 'Đã xử lý'), ('failed', 'Lỗi')], default='done', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Tắt để rút khỏi Radar ngay mà không phải xoá tài liệu', verbose_name='Đang hiệu lực')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tài liệu tri thức',
                'verbose_name_plural': 'Tài liệu tri thức',
                'ordering': ['-updated_at'],
            },
        ),
    ]
