# Generated by Django 4.2.23 on 2026-09-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeFeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_pk', models.BigIntegerField(db_index=True)),
                ('operation', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_events', to='knowledge.knowledgedocument')),
            ],
            options={
                'verbose_name': 'Sự kiện tri thức',
                'verbose_name_plural': 'Sự kiện tri thức',
                'ordering': ['pk'],
            },
        ),
    ]
