# Generated by Django 4.2.23 on 2026-08-19 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_interaction_actor_name_alter_interaction_actor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên pool')),
                ('description', models.TextField(blank=True, default='')),
                ('owner_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pool ứng viên',
                'verbose_name_plural': 'Pool ứng viên',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Tên nhãn')),
                ('slug', models.CharField(db_index=True, help_text='Bỏ dấu, chữ thường — để so khớp', max_length=60, unique=True)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nhãn',
                'verbose_name_plural': 'Nhãn',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='people.person')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='talent.pool')),
            ],
            options={
                'verbose_name': 'Thành viên pool',
                'verbose_name_plural': 'Thành viên pool',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='pool',
            name='members',
            field=models.ManyToManyField(related_name='pools', through='talent.PoolMembership', to='people.person'),
        ),
        migrations.AddField(
            model_name='pool',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Chức danh hiện tại')),
                ('current_company', models.CharField(blank=True, default='', max_length=200, verbose_name='Công ty hiện tại')),
                ('years_experience', models.FloatField(blank=True, null=True, verbose_name='Số năm kinh nghiệm')),
                ('seniority', models.CharField(blank=True, default='', max_length=40, verbose_name='Cấp bậc')),
                ('education', models.CharField(blank=True, default='', max_length=200, verbose_name='Học vấn')),
                ('expected_salary', models.CharField(blank=True, default='', max_length=100, verbose_name='Mức lương mong muốn')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Nơi ở')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Kỹ năng')),
                ('industries', models.JSONField(blank=True, default=list, verbose_name='Ngành từng làm')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Tóm tắt')),
                ('owner_name', models.CharField(blank=True, default='', max_length=150)),
                ('curated_fields', models.JSONField(blank=True, default=list, editable=False)),
                ('last_source_at', models.DateTimeField(blank=True, db_index=True, help_text='Lần cuối có dữ liệu mới từ nguồn', null=True)),
                ('derived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_talents', to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_profile', to='people.person')),
                ('tags', models.ManyToManyField(blank=True, related_name='talents', to='talent.tag')),
            ],
            options={
                'verbose_name': 'Hồ sơ Talent',
                'verbose_name_plural': 'Hồ sơ Talent',
                'ordering': ['-last_source_at'],
                'indexes': [models.Index(fields=['-last_source_at'], name='talent_tale_last_so_ca870d_idx'), models.Index(fields=['owner', '-updated_at'], name='talent_tale_owner_i_3facea_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='poolmembership',
            constraint=models.UniqueConstraint(fields=('pool', 'person'), name='uq_pool_person'),
        ),
    ]
