# Generated by Django 4.2.23 on 2026-08-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed', models.CharField(db_index=True, max_length=200, verbose_name='Chức danh cần tuyển')),
                ('candidate', models.CharField(max_length=200, verbose_name='Chức danh của ứng viên')),
                ('score', models.FloatField(help_text='0..1')),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('source', models.CharField(choices=[('llm', 'AI chấm'), ('string', 'So khớp chuỗi'), ('manual', 'Người sửa tay')], default='llm', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Độ gần chức danh',
                'verbose_name_plural': 'Độ gần chức danh',
                'ordering': ['needed', '-score'],
            },
        ),
        migrations.AddConstraint(
            model_name='titlesimilarity',
            constraint=models.UniqueConstraint(fields=('needed', 'candidate'), name='uq_titlesimilarity_pair'),
        ),
    ]
