# Generated by Django 4.2.23 on 2026-08-31 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_document_preview'),
        ('talent', '0004_talentaianalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentSemanticIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('normalized_text', models.TextField(blank=True, default='')),
                ('terms', models.JSONField(blank=True, default=list)),
                ('vector', models.JSONField(blank=True, default=dict)),
                ('source_characters', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_semantic_index', to='people.person')),
            ],
            options={
                'verbose_name': 'Chỉ mục semantic Talent',
                'verbose_name_plural': 'Chỉ mục semantic Talent',
                'indexes': [models.Index(fields=['-updated_at'], name='talent_tale_updated_64467f_idx')],
            },
        ),
    ]
