# Generated by Django 4.2.23 on 2026-09-02
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector
import pgvector.django.extensions


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0007_document_preview"),
        ("talent", "0005_talentsemanticindex"),
    ]

    operations = [
        pgvector.django.extensions.VectorExtension(),
        migrations.CreateModel(
            name="PersonSearchDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True,
                                              serialize=False, verbose_name="ID")),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("content", models.TextField(blank=True, default="")),
                ("embedding", pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ("embedding_model", models.CharField(blank=True, default="", max_length=120)),
                ("embedding_version", models.PositiveIntegerField(default=1)),
                ("indexed_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("person", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                    related_name="search_document", to="people.person")),
            ],
        ),
        migrations.CreateModel(
            name="CVChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True,
                                              serialize=False, verbose_name="ID")),
                ("ordinal", models.PositiveIntegerField()),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ("embedding_model", models.CharField(blank=True, default="", max_length=120)),
                ("embedding_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name="search_chunks", to="people.document")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name="cv_chunks", to="people.person")),
            ],
            options={"indexes": [models.Index(fields=["person", "document", "ordinal"],
                                                       name="talent_cvch_person__a19abe_idx")]},
        ),
        migrations.AddConstraint(
            model_name="cvchunk",
            constraint=models.UniqueConstraint(fields=("document", "ordinal"),
                                                name="uq_talent_cv_chunk_document_ordinal"),
        ),
    ]
