# Generated by Django 4.2.23 on 2026-09-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0009_radar_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='current_salary',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Mức lương hiện tại'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='desired_level',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cấp bậc mong muốn'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='desired_location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nơi làm việc mong muốn'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='desired_position',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ngành nghề/Vị trí mong muốn'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='foreign_language',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ngoại ngữ'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='job_type',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Hình thức làm việc mong muốn'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Tình trạng hôn nhân'),
        ),
    ]
