# Generated by Django 4.2.23 on 2026-09-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0010_talentprofile_current_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingconfig',
            name='greennode_model',
            field=models.CharField(blank=True, default='BAAI/bge-m3', max_length=120),
        ),
        migrations.AlterField(
            model_name='embeddingconfig',
            name='mode',
            field=models.CharField(choices=[('greennode', 'GreenNode MaaS (ưu tiên)'), ('selfhost', 'Tự host (Ollama / TEI)'), ('gemini', 'Google Gemini API'), ('off', 'Tắt — chỉ tìm full-text')], default='selfhost', max_length=20),
        ),
    ]
