# Generated by Django 4.2.23 on 2026-09-20 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_document_parse_retry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talent', '0012_intelligencedocumenttombstone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSetRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(db_index=True, default='interactive', max_length=20)),
                ('plan', models.JSONField(default=dict)),
                ('scope_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('population', models.PositiveIntegerField(default=0)),
                ('candidate_total', models.PositiveIntegerField(default=0)),
                ('scheduled', models.PositiveIntegerField(default=0)),
                ('judged', models.PositiveIntegerField(default=0)),
                ('unknown', models.PositiveIntegerField(default=0)),
                ('not_read', models.PositiveIntegerField(default=0)),
                ('pending', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('retrieval_degraded', models.BooleanField(default=False)),
                ('semantic_available', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('cost_used', models.JSONField(blank=True, default=dict)),
                ('explain', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_set_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaseDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('applications', models.JSONField(blank=True, default=list)),
                ('edge', models.JSONField(blank=True, default=list)),
                ('facts', models.JSONField(blank=True, default=list)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('lineage', models.JSONField(blank=True, default=list)),
                ('status', models.JSONField(blank=True, default=dict)),
                ('built_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_dossier', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='SearchProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('title_norm', models.CharField(blank=True, db_index=True, default='', max_length=240)),
                ('company_norm', models.CharField(blank=True, db_index=True, default='', max_length=240)),
                ('location_norm', models.CharField(blank=True, db_index=True, default='', max_length=240)),
                ('education_norm', models.CharField(blank=True, db_index=True, default='', max_length=240)),
                ('skills_norm', models.JSONField(blank=True, default=list)),
                ('industries_norm', models.JSONField(blank=True, default=list)),
                ('source_channels', models.JSONField(blank=True, default=list)),
                ('application_positions', models.JSONField(blank=True, default=list)),
                ('years_experience', models.FloatField(blank=True, db_index=True, null=True)),
                ('last_application_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('searchable_text', models.TextField(blank=True, default='')),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('built_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='typed_search_projection', to='people.person')),
            ],
            options={
                'indexes': [models.Index(fields=['version', 'title_norm'], name='talent_sear_version_d1f006_idx'), models.Index(fields=['version', 'location_norm'], name='talent_sear_version_642b8b_idx'), models.Index(fields=['version', 'years_experience'], name='talent_sear_version_d3e188_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConstraintJudgementCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('dossier_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('constraint_canonical', models.TextField()),
                ('scope_token', models.CharField(db_index=True, max_length=64)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
                ('judgement', models.JSONField(default=dict)),
                ('complete', models.BooleanField(db_index=True, default=False)),
                ('token_usage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraint_judgement_cache', to='people.person')),
            ],
            options={
                'indexes': [models.Index(fields=['person', 'dossier_fingerprint'], name='talent_cons_person__8c4917_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateSetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField(db_index=True)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('structured_score', models.FloatField(blank=True, null=True)),
                ('lexical_score', models.FloatField(blank=True, null=True)),
                ('semantic_score', models.FloatField(blank=True, null=True)),
                ('deterministic_status', models.CharField(blank=True, db_index=True, default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_set_memberships', to='people.person')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='talent.candidatesetrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'ordinal'], name='talent_cand_run_id_62517b_idx'), models.Index(fields=['run', 'deterministic_status'], name='talent_cand_run_id_00200c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='candidatesetmember',
            constraint=models.UniqueConstraint(fields=('run', 'person'), name='uq_candidate_set_run_person'),
        ),
    ]
