# Generated by Django 4.2.23 on 2026-09-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0013_candidatesetrun_basedossier_searchprojection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesetrun',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatesetrun',
            name='cursor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatesetrun',
            name='error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='candidatesetrun',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatesetrun',
            name='state',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
    ]
