# Generated by Django 4.2.23 on 2026-09-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0016_searchprojection_field_fts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=20)),
                ('canonical', models.CharField(max_length=240)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('updated_by', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'enabled'], name='talent_sear_kind_58bc9c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='searchvocabulary',
            constraint=models.UniqueConstraint(fields=('kind', 'canonical'), name='uq_search_vocab_kind_canonical'),
        ),
    ]
