# Generated by Django 4.2.23 on 2026-08-20 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0003_alter_document_options_document_file_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Vị trí cần tuyển')),
                ('department', models.CharField(blank=True, default='', max_length=150, verbose_name='Bộ phận')),
                ('jd_text', models.TextField(blank=True, default='', help_text='Dán JD vào đây; hệ thống tự rút ra tiêu chí', verbose_name='Mô tả công việc')),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('criteria_fallback', models.BooleanField(default=False)),
                ('learned_weights', models.JSONField(blank=True, default=dict, editable=False)),
                ('calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('open', 'Đang mở'), ('hunting', 'Đã nhờ recruiter săn'), ('closed', 'Đã đóng')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_needs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhu cầu tuyển dụng',
                'verbose_name_plural': 'Nhu cầu tuyển dụng',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('suggested', 'Hệ thống đề xuất'), ('good_fit', 'Phù hợp'), ('not_fit', 'Không phù hợp'), ('shortlisted', 'Đưa vào shortlist')], db_index=True, default='suggested', max_length=20)),
                ('score_snapshot', models.FloatField(default=0.0)),
                ('dimensions_snapshot', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('marked_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hiring_need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='hiring.hiringneed')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='people.person')),
            ],
            options={
                'verbose_name': 'Ứng viên cho vị trí',
                'verbose_name_plural': 'Ứng viên cho vị trí',
                'ordering': ['-score_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='HuntRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('assigned_to_name', models.CharField(blank=True, default='', max_length=150)),
                ('message', models.TextField(blank=True, default='', verbose_name='Lời nhắn cho recruiter')),
                ('status', models.CharField(choices=[('new', 'Mới, chưa ai nhận'), ('accepted', 'Recruiter đã nhận'), ('in_progress', 'Đang liên hệ ứng viên'), ('done', 'Đã xong'), ('declined', 'Từ chối')], db_index=True, default='new', max_length=20)),
                ('decline_reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hunts', to=settings.AUTH_USER_MODEL)),
                ('hiring_need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_requests', to='hiring.hiringneed')),
                ('people', models.ManyToManyField(blank=True, help_text='Shortlist HM gửi kèm', related_name='hunt_requests', to='people.person')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunt_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu săn ứng viên',
                'verbose_name_plural': 'Yêu cầu săn ứng viên',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='hiring_hunt_status_4139ab_idx'), models.Index(fields=['assigned_to', 'status'], name='hiring_hunt_assigne_f5f01c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='hiringneed',
            index=models.Index(fields=['owner', '-updated_at'], name='hiring_hiri_owner_i_296e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='candidacy',
            index=models.Index(fields=['hiring_need', 'state'], name='hiring_cand_hiring__90fd39_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidacy',
            constraint=models.UniqueConstraint(fields=('hiring_need', 'person'), name='uq_candidacy_need_person'),
        ),
    ]
