# Generated by Django 4.2.23 on 2026-08-20 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0003_alter_document_options_document_file_size_and_more'),
        ('hiring', '0001_initial'),
    ]

    # Django không đổi được M2M thường thành M2M có `through=` bằng AlterField
    # ("you cannot ... add or remove through= on M2M fields"). Nên phải BỎ hẳn
    # trường cũ rồi thêm lại. Bảng nối cũ bị xoá theo — chấp nhận được vì Phase 8
    # mới lên hôm nay và chưa có dữ liệu săn nào ở môi trường thật.
    operations = [
        migrations.RemoveField(
            model_name='huntrequest',
            name='people',
        ),
        migrations.CreateModel(
            name='HuntCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Chưa liên hệ'), ('contacting', 'Đang liên hệ'), ('responded', 'Đã phản hồi'), ('interested', 'Quan tâm'), ('not_interested', 'Không quan tâm'), ('unreachable', 'Không liên hệ được'), ('submitted', 'Đã chuyển cho HM'), ('returned', 'Trả về kho talent')], db_index=True, default='pending', max_length=20)),
                ('outreach_draft', models.TextField(blank=True, default='')),
                ('outreach_sent_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('return_reason', models.CharField(blank=True, default='', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hunt_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='hiring.huntrequest')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_candidates', to='people.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ứng viên trong yêu cầu săn',
                'verbose_name_plural': 'Ứng viên trong yêu cầu săn',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='huntrequest',
            name='people',
            field=models.ManyToManyField(blank=True, help_text='Shortlist HM gửi kèm', related_name='hunt_requests', through='hiring.HuntCandidate', to='people.person'),
        ),
        migrations.AddIndex(
            model_name='huntcandidate',
            index=models.Index(fields=['hunt_request', 'state'], name='hiring_hunt_hunt_re_6da0b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='huntcandidate',
            constraint=models.UniqueConstraint(fields=('hunt_request', 'person'), name='uq_huntcandidate_hunt_person'),
        ),
    ]
