# Generated by Django 4.2.23 on 2026-08-22 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hiring', '0003_shortlist_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntcandidate',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hunt_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='huntcandidate',
            name='assigned_to_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='HuntCandidateStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, default='', max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='hiring.huntcandidate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate', '-created_at'], name='hiring_hunt_candida_d7b4ea_idx')],
            },
        ),
    ]
