# Generated by Django 4.2.23 on 2026-08-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0004_huntcandidate_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntcandidate',
            name='state',
            field=models.CharField(choices=[('pending', 'Mới trong danh sách'), ('contacting', 'Đang liên hệ'), ('responded', 'Đã phản hồi'), ('interested', 'Có quan tâm'), ('not_interested', 'Chưa quan tâm'), ('unreachable', 'Không liên hệ được'), ('submitted', 'Hoàn tất mục tiêu'), ('returned', 'Đưa về chăm sóc dài hạn')], db_index=True, default='pending', max_length=20),
        ),
    ]
