# Generated by Django 4.2.23 on 2026-08-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('task', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('ok', models.BooleanField(db_index=True, default=True)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Lượt gọi LLM',
                'verbose_name_plural': 'Lượt gọi LLM',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', '-created_at'], name='ai_llmcall_provide_e729a9_idx')],
            },
        ),
    ]
