# Generated by Django 4.2.23 on 2026-08-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('greennode', 'GreenNode'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek')], max_length=40, unique=True, verbose_name='Nhà cung cấp')),
                ('enabled', models.BooleanField(default=True, verbose_name='Đang bật')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Số nhỏ được thử trước. GreenNode nên để nhỏ nhất.', verbose_name='Thứ tự ưu tiên')),
                ('api_key_encrypted', models.TextField(blank=True, default='', editable=False)),
                ('api_key_hint', models.CharField(blank=True, default='', editable=False, max_length=60, verbose_name='Khoá (che)')),
                ('base_url', models.CharField(blank=True, default='', help_text='Để trống = dùng mặc định của nhà cung cấp', max_length=300, verbose_name='Base URL')),
                ('model', models.CharField(blank=True, default='', max_length=120, verbose_name='Mã model')),
                ('timeout', models.PositiveIntegerField(default=60, verbose_name='Thời gian chờ (giây)')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_check_ok', models.BooleanField(blank=True, null=True)),
                ('last_check_detail', models.CharField(blank=True, default='', max_length=400)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình nhà cung cấp AI',
                'verbose_name_plural': 'Cấu hình nhà cung cấp AI',
                'ordering': ['priority', 'provider'],
            },
        ),
    ]
