# Generated by Django 4.2.23 on 2026-08-31 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0002_providerconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, max_length=64)),
                ('surface', models.CharField(choices=[('talent', 'Talent'), ('prospect', 'Growth')], max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('state', models.JSONField(blank=True, default=dict)),
                ('turns', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'surface', '-updated_at'], name='ai_assistan_user_id_8ae1dc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='assistantthread',
            constraint=models.UniqueConstraint(fields=('user', 'surface', 'thread_id'), name='uq_assistant_thread'),
        ),
    ]
