# Generated by Django 4.2.23 on 2026-08-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_assistantthread_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='client_turn_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='assistantmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_turn_id__gt', '')), fields=('thread', 'client_turn_id'), name='uq_assistant_msg_client_turn'),
        ),
    ]
