# Generated by Django 4.2.23 on 2026-08-31 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_assistantmessage_client_turn_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_id', models.CharField(db_index=True, max_length=64)),
                ('seq', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('turn.started', 'Bắt đầu lượt'), ('user.message', 'Tin nhắn người dùng'), ('model.requested', 'Gửi model'), ('model.responded', 'Model trả lời'), ('search.executed', 'Đã tìm kiếm'), ('search.results_ranked', 'Đã xếp hạng kết quả'), ('turn.completed', 'Kết thúc lượt'), ('turn.failed', 'Lượt lỗi')], db_index=True, max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ai.assistantthread')),
            ],
            options={
                'ordering': ['thread_id', 'turn_id', 'seq', 'pk'],
                'indexes': [models.Index(fields=['thread', 'turn_id', 'seq'], name='ai_assistan_thread__65ce92_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='assistantevent',
            constraint=models.UniqueConstraint(fields=('thread', 'turn_id', 'seq'), name='uq_assistant_event_seq'),
        ),
    ]
