# Generated by Django 4.2.23 on 2026-08-31 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0006_assistantevent_assistantevent_uq_assistant_event_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('preference', 'Sở thích trình bày'), ('fact', 'Sự việc')], default='fact', max_length=20)),
                ('key', models.CharField(blank=True, default='', max_length=80)),
                ('value', models.TextField()),
                ('source', models.CharField(blank=True, default='user', help_text='user | admin', max_length=40)),
                ('surface', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ghi nhớ dài hạn',
                'verbose_name_plural': 'Ghi nhớ dài hạn',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('up', 'Hữu ích'), ('down', 'Chưa tốt')], db_index=True, max_length=8)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('question', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
                ('surface', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='ai.assistantmessage')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='ai.assistantthread')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phản hồi trợ lý',
                'verbose_name_plural': 'Phản hồi trợ lý',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='longtermmemory',
            constraint=models.UniqueConstraint(condition=models.Q(('key__gt', '')), fields=('user', 'key'), name='uq_longterm_memory_key'),
        ),
        migrations.AddConstraint(
            model_name='assistantfeedback',
            constraint=models.UniqueConstraint(condition=models.Q(('message__isnull', False)), fields=('message', 'user'), name='uq_assistant_feedback_msg_user'),
        ),
    ]
