# Generated by Django 4.2.23 on 2026-09-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_longtermmemory_assistantfeedback_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='longtermmemory',
            name='uq_longterm_memory_key',
        ),
        migrations.AddField(
            model_name='longtermmemory',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='longtermmemory',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='longtermmemory',
            name='scope',
            field=models.CharField(choices=[('profile', 'Hồ sơ người dùng'), ('operational', 'Quy ước vận hành Radar')], db_index=True, default='operational', max_length=20),
        ),
        migrations.AddField(
            model_name='longtermmemory',
            name='status',
            field=models.CharField(choices=[('active', 'Đang dùng'), ('pending_review', 'Chờ người dùng duyệt'), ('rejected', 'Đã bỏ')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='longtermmemory',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='longtermmemory',
            name='source',
            field=models.CharField(blank=True, default='user', help_text='user | admin | radar_ai', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='longtermmemory',
            constraint=models.UniqueConstraint(condition=models.Q(('key__gt', '')), fields=('user', 'scope', 'key'), name='uq_longterm_memory_key'),
        ),
    ]
