# Generated by Django 4.2.23 on 2026-09-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_alter_assistantevent_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantevent',
            name='kind',
            field=models.CharField(choices=[('turn.started', 'Bắt đầu lượt'), ('user.message', 'Tin nhắn người dùng'), ('intent.classified', 'Đã phân loại ý định'), ('model.requested', 'Gửi model'), ('model.responded', 'Model trả lời'), ('search.executed', 'Đã tìm kiếm'), ('search.results_ranked', 'Đã xếp hạng kết quả'), ('web.searched', 'Đã tra Google'), ('tool.called', 'Đã gọi tool'), ('turn.completed', 'Kết thúc lượt'), ('turn.failed', 'Lượt lỗi')], db_index=True, max_length=40),
        ),
    ]
