# Generated by Django 4.2.23 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0010_alter_assistantevent_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskModelRoute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True,
                                              serialize=False, verbose_name="ID")),
                ("task", models.CharField(db_index=True, max_length=60, unique=True)),
                ("provider", models.CharField(choices=[("greennode", "GreenNode"),
                    ("openai", "OpenAI"), ("gemini", "Google Gemini"),
                    ("deepseek", "DeepSeek")], max_length=40)),
                ("model", models.CharField(blank=True, default="", max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                ("updated_by", models.CharField(blank=True, default="", max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Điều hướng model theo tác vụ",
                     "verbose_name_plural": "Điều hướng model theo tác vụ",
                     "ordering": ["task"]},
        ),
    ]
