# Generated by Django 4.2.23 on 2026-09-09 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0017_route_cv_reference_extraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_turn_id', models.CharField(max_length=64)),
                ('state', models.CharField(default='running', max_length=12)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='answerrun',
            constraint=models.UniqueConstraint(fields=('user', 'client_turn_id'), name='uq_answer_run_user_turn'),
        ),
    ]
