# Generated by Django 4.2.23 on 2026-09-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0026_route_candidate_extraction_benchmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrun',
            name='coverage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
