# Generated by Django 4.2.23 on 2026-08-31 20:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_databasebackuplog'),
        ('people', '0007_document_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalNamespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('normalization_version', models.PositiveIntegerField(default=1)),
                ('fold_diacritics', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục chuẩn',
                'verbose_name_plural': 'Danh mục chuẩn',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='MaterializedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_version', models.PositiveIntegerField(db_index=True, default=1)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('codes', models.JSONField(blank=True, default=dict)),
                ('fact_count', models.PositiveIntegerField(default=0)),
                ('built_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materialized', to='people.person')),
            ],
            options={
                'verbose_name': 'Ảnh tìm kiếm',
                'verbose_name_plural': 'Ảnh tìm kiếm',
            },
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Đang chạy'), ('done', 'Xong'), ('failed', 'Lỗi')], db_index=True, default='running', max_length=20)),
                ('extractor', models.CharField(default='edge_first', max_length=40)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('dry_run', models.BooleanField(default=False)),
                ('coverage', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='people.person')),
            ],
            options={
                'verbose_name': 'Lượt trích xuất',
                'verbose_name_plural': 'Lượt trích xuất',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Chờ'), ('leased', 'Đang xử lý'), ('done', 'Xong'), ('failed', 'Lỗi')], db_index=True, default='queued', max_length=20)),
                ('batch', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('use_ai', models.BooleanField(default=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('lease_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('worker', models.CharField(blank=True, default='', max_length=80)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('enqueued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='intel.extractionrun')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='people.person')),
            ],
            options={
                'verbose_name': 'Việc trích xuất',
                'verbose_name_plural': 'Việc trích xuất',
                'ordering': ['enqueued_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(db_index=True, max_length=60)),
                ('raw_value', models.CharField(blank=True, default='', max_length=500)),
                ('normalized_value', models.CharField(blank=True, default='', max_length=500)),
                ('canonical_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('canonical_label', models.CharField(blank=True, default='', max_length=200)),
                ('confidence', models.FloatField(default=0.0, help_text='0..1')),
                ('source_kind', models.CharField(choices=[('edge', 'Edge payload'), ('cv_text', 'Text CV đã parsing'), ('profile', 'Hồ sơ hiện có'), ('ai', 'AI suy luận'), ('manual', 'Người nhập/sửa tay')], db_index=True, max_length=20)),
                ('evidence', models.TextField(blank=True, default='', help_text='Trích dẫn đủ để người dùng kiểm tra')),
                ('extractor', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('observed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('proposed', 'Đề xuất'), ('accepted', 'Đã chấp nhận'), ('rejected', 'Đã bác'), ('conflict', 'Mâu thuẫn')], db_index=True, default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='people.document')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='people.person')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='intel.extractionrun')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='core.sourcerecord')),
            ],
            options={
                'verbose_name': 'Fact có nguồn',
                'verbose_name_plural': 'Fact có nguồn',
                'ordering': ['person_id', 'field', '-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('attrs', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='intel.canonicalnamespace')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='intel.canonicalentry')),
            ],
            options={
                'verbose_name': 'Mã chuẩn',
                'verbose_name_plural': 'Mã chuẩn',
                'ordering': ['namespace__key', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_norm', models.CharField(db_index=True, help_text='Đã chuẩn hoá theo namespace', max_length=200)),
                ('alias_raw', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('proposed', 'Đề xuất — chờ duyệt'), ('accepted', 'Đã duyệt'), ('rejected', 'Đã bác')], db_index=True, default='proposed', max_length=20)),
                ('source', models.CharField(blank=True, default='', help_text='seed | code | radar_ai | admin', max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('approved_by', models.CharField(blank=True, default='', max_length=150)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('previous', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='intel.canonicalentry')),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='intel.canonicalnamespace')),
            ],
            options={
                'verbose_name': 'Alias chuẩn',
                'verbose_name_plural': 'Alias chuẩn',
                'ordering': ['namespace__key', 'alias_norm'],
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, default='', max_length=60)),
                ('reason', models.CharField(choices=[('sensitive', 'Trường nhạy cảm'), ('low_confidence', 'Độ tin cậy thấp'), ('conflict', 'Giá trị mâu thuẫn'), ('unknown_alias', 'Alias chưa nhận diện')], db_index=True, max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('open', 'Chờ xử lý'), ('accepted', 'Đã nhận'), ('rejected', 'Đã bác')], db_index=True, default='open', max_length=20)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=150)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='intel.canonicalalias')),
                ('fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='intel.extractedfact')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='people.person')),
            ],
            options={
                'verbose_name': 'Mục chờ duyệt',
                'verbose_name_plural': 'Mục chờ duyệt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'reason', '-created_at'], name='intel_revie_status_b56dc4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='extractionrun',
            index=models.Index(fields=['person', '-started_at'], name='intel_extra_person__51dec4_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['status', 'enqueued_at'], name='intel_extra_status_dadada_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractionjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'leased'])), fields=('person',), name='uq_extraction_job_pending'),
        ),
        migrations.AddIndex(
            model_name='extractedfact',
            index=models.Index(fields=['person', 'field', 'status'], name='intel_extra_person__aa1cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedfact',
            index=models.Index(fields=['person', 'field', 'is_current'], name='intel_extra_person__41ece0_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractedfact',
            constraint=models.UniqueConstraint(fields=('fingerprint',), name='uq_extracted_fact_fp'),
        ),
        migrations.AddIndex(
            model_name='canonicalentry',
            index=models.Index(fields=['namespace', 'active'], name='intel_canon_namespa_be2966_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicalentry',
            constraint=models.UniqueConstraint(fields=('namespace', 'code'), name='uq_canonical_entry'),
        ),
        migrations.AddIndex(
            model_name='canonicalalias',
            index=models.Index(fields=['namespace', 'status'], name='intel_canon_namespa_e3f32e_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicalalias',
            constraint=models.UniqueConstraint(fields=('namespace', 'alias_norm'), name='uq_canonical_alias'),
        ),
    ]
