# Generated by Django 4.2.23 on 2026-08-20 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hiring', '0002_huntcandidate_alter_huntrequest_people_and_more'),
        ('people', '0003_alter_document_options_document_file_size_and_more'),
        ('core', '0002_sourcerecord_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('zalo', 'Zalo'), ('linkedin', 'LinkedIn')], default='facebook', max_length=20)),
                ('external_id', models.CharField(max_length=200, verbose_name='Mã trên nền tảng')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, default='')),
                ('topic', models.CharField(blank=True, default='', max_length=200, verbose_name='Chủ đề')),
                ('member_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nhóm/trang theo dõi',
                'verbose_name_plural': 'Nhóm/trang theo dõi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('zalo', 'Zalo'), ('linkedin', 'LinkedIn')], default='facebook', max_length=20)),
                ('label', models.CharField(max_length=150, verbose_name='Tên gợi nhớ')),
                ('handle', models.CharField(blank=True, default='', max_length=200, verbose_name='Tên tài khoản')),
                ('purpose', models.CharField(choices=[('listen', 'Chỉ nghe'), ('engage', 'Nghe và tương tác')], default='listen', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to='core.edge')),
            ],
            options={
                'verbose_name': 'Tài khoản mạng xã hội',
                'verbose_name_plural': 'Tài khoản mạng xã hội',
                'ordering': ['provider', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('zalo', 'Zalo'), ('linkedin', 'LinkedIn')], default='facebook', max_length=20)),
                ('external_id', models.CharField(max_length=200, verbose_name='Mã bài trên nền tảng')),
                ('author_name', models.CharField(blank=True, default='', max_length=200)),
                ('author_handle', models.CharField(blank=True, default='', max_length=200)),
                ('author_url', models.URLField(blank=True, default='')),
                ('content', models.TextField()),
                ('url', models.URLField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('intent', models.JSONField(blank=True, default=dict)),
                ('intent_reason', models.CharField(blank=True, default='', max_length=500)),
                ('intent_fallback', models.BooleanField(default=False, help_text='Điểm do dò từ khoá vì không gọi được LLM')),
                ('contacts', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'Mới bắt được'), ('scored', 'Đã chấm ý định'), ('linked', 'Đã gắn với hồ sơ người'), ('ignored', 'Không liên quan')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='social.socialaccount')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='social.community')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='people.person')),
            ],
            options={
                'verbose_name': 'Bài trên mạng xã hội',
                'verbose_name_plural': 'Bài trên mạng xã hội',
                'ordering': ['-posted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('author_name', models.CharField(blank=True, default='', max_length=200)),
                ('author_handle', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.socialpost')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['posted_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('comment', 'Bình luận vào bài'), ('message', 'Nhắn tin riêng'), ('seed_post', 'Đăng bài tuyển dụng')], default='comment', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'AI soạn nháp'), ('approved', 'Đã duyệt'), ('posted', 'Đã đăng/gửi'), ('discarded', 'Bỏ')], db_index=True, default='draft', max_length=20)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='social.community')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hiring_need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_actions', to='hiring.hiringneed')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='social.socialpost')),
            ],
            options={
                'verbose_name': 'Hành động trên mạng xã hội',
                'verbose_name_plural': 'Hành động trên mạng xã hội',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='community',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='social.socialaccount'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['status', '-created_at'], name='social_soci_status_9f8846_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['community', '-posted_at'], name='social_soci_communi_758781_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialpost',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='uq_socialpost_provider_external'),
        ),
        migrations.AddConstraint(
            model_name='community',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='uq_community_provider_external'),
        ),
    ]
