# Generated by Django 4.2.23 on 2026-08-19 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Tên hiển thị')),
                ('normalized_name', models.CharField(blank=True, db_index=True, default='', help_text='Bỏ dấu, chữ thường — chỉ để gợi ý trùng lặp', max_length=200)),
                ('primary_email', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('primary_phone', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('headline', models.CharField(blank=True, default='', max_length=200, verbose_name='Vị trí gần nhất')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Nơi ở')),
                ('needs_review', models.BooleanField(db_index=True, default=False, help_text='Có xung đột định danh chưa xử lý', verbose_name='Cần người xem lại')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, help_text='Đã gộp vào Person này; giữ lại để không vỡ liên kết cũ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='people.person')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Person',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('talent', 'Tuyển dụng'), ('rb', 'Bán lẻ')], default='talent', max_length=20)),
                ('signal_type', models.CharField(db_index=True, max_length=60)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('confidence', models.FloatField(default=0.0, help_text='0..1')),
                ('evidence', models.JSONField(default=dict)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('new', 'Mới'), ('acted', 'Đã xử lý'), ('ignored', 'Bỏ qua')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='people.person')),
            ],
            options={
                'verbose_name': 'Tín hiệu',
                'verbose_name_plural': 'Tín hiệu',
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('talent', 'Tuyển dụng'), ('rb', 'Bán lẻ')], max_length=20)),
                ('state', models.CharField(max_length=40)),
                ('owner', models.CharField(blank=True, default='', help_text='Recruiter hoặc RM phụ trách', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='people.person')),
            ],
            options={
                'verbose_name': 'Quan hệ',
                'verbose_name_plural': 'Quan hệ',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('talent', 'Tuyển dụng'), ('rb', 'Bán lẻ')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('score', models.FloatField(default=0.0, help_text='0..1, do hệ thống chấm')),
                ('confidence', models.FloatField(default=0.0, help_text='0..1')),
                ('why', models.JSONField(default=dict, help_text='FACT / INFERENCE / UNKNOWN')),
                ('recommended_action', models.CharField(blank=True, default='', max_length=200)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Phần riêng của từng nghiệp vụ')),
                ('owner', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('open', 'Đang mở'), ('accepted', 'Đã nhận'), ('rejected', 'Từ chối'), ('done', 'Hoàn tất')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='people.person')),
                ('signals', models.ManyToManyField(blank=True, related_name='opportunities', to='people.signal')),
            ],
            options={
                'verbose_name': 'Cơ hội',
                'verbose_name_plural': 'Cơ hội',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('talent', 'Tuyển dụng'), ('rb', 'Bán lẻ')], default='talent', max_length=20)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('actor', models.CharField(blank=True, default='', max_length=150)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='people.person')),
            ],
            options={
                'verbose_name': 'Tương tác',
                'verbose_name_plural': 'Tương tác',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.JSONField(default=dict, help_text='Các định danh dẫn tới xung đột và Person tương ứng')),
                ('source_record_id', models.CharField(blank=True, default='', help_text='Bản ghi nguồn làm lộ ra xung đột', max_length=64)),
                ('status', models.CharField(choices=[('open', 'Chờ xử lý'), ('merged', 'Đã gộp'), ('dismissed', 'Đã bỏ qua — hai người khác nhau')], db_index=True, default='open', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('people', models.ManyToManyField(related_name='conflicts', to='people.person')),
            ],
            options={
                'verbose_name': 'Xung đột định danh',
                'verbose_name_plural': 'Xung đột định danh',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('email', 'Email'), ('phone', 'Điện thoại'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('provider_person_id', 'Mã ứng viên của nguồn')], max_length=32, verbose_name='Loại')),
                ('value', models.CharField(max_length=300, verbose_name='Giá trị đã chuẩn hoá')),
                ('raw_value', models.CharField(blank=True, default='', max_length=300, verbose_name='Giá trị gốc')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='people.person')),
            ],
            options={
                'verbose_name': 'Định danh',
                'verbose_name_plural': 'Định danh',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(default='cv', max_length=40)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('filename', models.CharField(blank=True, default='', max_length=300)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('sha256', models.CharField(db_index=True, help_text='Khử trùng lặp: cùng một file tải từ hai nguồn', max_length=64)),
                ('storage_key', models.CharField(blank=True, default='', help_text='Khoá trên Cloudflare R2; trống nếu chưa tải lên', max_length=500)),
                ('parsed_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='people.person')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Tài liệu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['domain', 'status', '-observed_at'], name='people_sign_domain_810f48_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['person', '-observed_at'], name='people_sign_person__e7c5a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('person', 'domain'), name='uq_relationship_person_domain'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['needs_review', '-updated_at'], name='people_pers_needs_r_34fc06_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['domain', 'status', '-score'], name='people_oppo_domain_da9bff_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['person', '-occurred_at'], name='people_inte_person__9963aa_idx'),
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['person', 'kind'], name='people_iden_person__a84936_idx'),
        ),
        migrations.AddConstraint(
            model_name='identity',
            constraint=models.UniqueConstraint(fields=('kind', 'value'), name='uq_identity_kind_value'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('person', 'sha256'), name='uq_document_person_hash'),
        ),
    ]
