# Generated by Django 4.2.23 on 2026-08-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sourcerecord_person'),
        ('people', '0002_interaction_actor_name_alter_interaction_actor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-observed_at', '-created_at'], 'verbose_name': 'Tài liệu', 'verbose_name_plural': 'Tài liệu'},
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='observed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='parse_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='quality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='source_records',
            field=models.ManyToManyField(blank=True, related_name='documents', to='core.sourcerecord'),
        ),
        migrations.AddField(
            model_name='document',
            name='text_length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Nguồn của lần đầu nhìn thấy file này', max_length=40),
        ),
        migrations.AlterField(
            model_name='document',
            name='storage_key',
            field=models.CharField(blank=True, default='', help_text='Khoá trong kho file; trống = Edge chưa tải lên', max_length=500),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['person', '-observed_at'], name='people_docu_person__9157c9_idx'),
        ),
    ]
