# Generated by Django 4.2.23 on 2026-08-31 05:33

from django.db import migrations, models
import django.db.models.deletion


def migrate_legacy_text(apps, schema_editor):
    import hashlib
    import re
    import unicodedata

    Document = apps.get_model('people', 'Document')
    Version = apps.get_model('people', 'ParsedTextVersion')
    Link = apps.get_model('people', 'DocumentTextLink')
    for document in Document.objects.exclude(parsed_text='').iterator():
        lines = [re.sub(r'[ \t]+', ' ', line).strip() for line in
                 unicodedata.normalize('NFKC', document.parsed_text)
                 .replace('\r\n', '\n').replace('\r', '\n').split('\n')]
        text = re.sub(r'\n{3,}', '\n\n', '\n'.join(lines).strip())
        if not text:
            continue
        digest = hashlib.sha256(text.encode('utf-8')).hexdigest()
        version, _ = Version.objects.get_or_create(
            person_id=document.person_id, text_hash=digest,
            defaults={'text': text, 'text_length': len(text)})
        Link.objects.get_or_create(
            document_id=document.pk, text_version_id=version.pk,
            defaults={'origins': ['legacy'], 'provider': 'legacy',
                      'quality_score': document.quality_score})
        document.primary_text_version_id = version.pk
        document.text_length = len(text)
        document.parsed_text = ''
        document.save(update_fields=['primary_text_version', 'text_length', 'parsed_text'])


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_relationship_operational_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parse_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='parse_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='parse_provider',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='document',
            name='parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ParsedTextVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hash', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('text_length', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_text_versions', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTextLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origins', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('quality_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_links', to='people.document')),
                ('text_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='people.parsedtextversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='primary_text_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_documents', to='people.parsedtextversion'),
        ),
        migrations.AddIndex(
            model_name='parsedtextversion',
            index=models.Index(fields=['person', '-created_at'], name='people_pars_person__a05578_idx'),
        ),
        migrations.AddConstraint(
            model_name='parsedtextversion',
            constraint=models.UniqueConstraint(fields=('person', 'text_hash'), name='uq_parsed_text_person_hash'),
        ),
        migrations.AddConstraint(
            model_name='documenttextlink',
            constraint=models.UniqueConstraint(fields=('document', 'text_version'), name='uq_document_text_version'),
        ),
        migrations.RunPython(migrate_legacy_text, migrations.RunPython.noop),
    ]
