# Generated by Django 4.2.23 on 2026-08-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_parsed_text_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='preview_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='preview_key',
            field=models.CharField(blank=True, default='', help_text='Bản PDF xem trước do Hub tạo, tách khỏi file gốc', max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='preview_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='previewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
