# Generated by Django 4.2.23 on 2026-09-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_document_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('relationship_note', models.CharField(blank=True, default='', help_text='CV mô tả quan hệ thế nào', max_length=200)),
                ('email_raw', models.CharField(blank=True, default='', max_length=300)),
                ('phone_raw', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('kind', models.CharField(choices=[('reference', 'Người tham chiếu'), ('referrer', 'Người giới thiệu'), ('emergency', 'Liên hệ khẩn cấp'), ('self', 'Của chính ứng viên')], default='reference', max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='0..1')),
                ('evidence', models.TextField(blank=True, default='')),
                ('extractor', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('proposed', 'Chờ duyệt'), ('accepted', 'Đã nhận'), ('rejected', 'Đã loại')], db_index=True, default='proposed', max_length=20)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Liên hệ nhắc tới trong tài liệu',
                'verbose_name_plural': 'Liên hệ nhắc tới trong tài liệu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reference', 'Người tham chiếu'), ('referred_by', 'Được giới thiệu bởi'), ('colleague', 'Đồng nghiệp'), ('manager', 'Quản lý cũ'), ('same_employer', 'Cùng nơi làm việc')], db_index=True, max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='0..1')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quan hệ giữa người với người',
                'verbose_name_plural': 'Quan hệ giữa người với người',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='is_applicant',
            field=models.BooleanField(db_index=True, default=True, help_text='Hiện trong các bề mặt tuyển dụng', verbose_name='Đã từng ứng tuyển'),
        ),
        migrations.AddField(
            model_name='person',
            name='origin',
            field=models.CharField(choices=[('application', 'Từ lượt ứng tuyển'), ('cv_reference', 'Người tham chiếu trong CV'), ('manual', 'Nhập tay')], db_index=True, default='application', help_text='Lần đầu gặp người này ở đâu — không đổi về sau', max_length=20, verbose_name='Biết đến qua'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_applicant', '-updated_at'], name='people_pers_is_appl_a94121_idx'),
        ),
        migrations.AddField(
            model_name='personlink',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='people.person'),
        ),
        migrations.AddField(
            model_name='personlink',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_links', to='people.document'),
        ),
        migrations.AddField(
            model_name='personlink',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='people.person'),
        ),
        migrations.AddField(
            model_name='contactmention',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_mentions', to='people.document'),
        ),
        migrations.AddField(
            model_name='contactmention',
            name='linked_person',
            field=models.ForeignKey(blank=True, help_text='Person đã tạo/khớp từ bản ghi này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_as', to='people.person'),
        ),
        migrations.AddField(
            model_name='contactmention',
            name='subject',
            field=models.ForeignKey(help_text='Người mà tài liệu này nói về (ứng viên)', on_delete=django.db.models.deletion.CASCADE, related_name='contact_mentions', to='people.person'),
        ),
        migrations.AddIndex(
            model_name='personlink',
            index=models.Index(fields=['related', 'kind'], name='people_pers_related_67ccdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='personlink',
            constraint=models.UniqueConstraint(fields=('subject', 'related', 'kind'), name='uq_person_link'),
        ),
        migrations.AddConstraint(
            model_name='personlink',
            constraint=models.CheckConstraint(check=models.Q(('subject', models.F('related')), _negated=True), name='ck_person_link_khac_nguoi'),
        ),
        migrations.AddIndex(
            model_name='contactmention',
            index=models.Index(fields=['subject', 'status'], name='people_cont_subject_dd994e_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmention',
            index=models.Index(fields=['status', '-created_at'], name='people_cont_status_f48cde_idx'),
        ),
    ]
