# Generated by Django 4.2.23 on 2026-08-20 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('talent', 'Talent Radar Agent'), ('rb', 'RB Radar Agent'), ('social', 'Social Intent Agent')], db_index=True, max_length=20)),
                ('goal', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('running', 'Đang chạy'), ('ok', 'Xong'), ('error', 'Lỗi')], db_index=True, default='running', max_length=20)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lượt chạy Agent',
                'verbose_name_plural': 'Lượt chạy Agent',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('tool', models.CharField(blank=True, default='', max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('ok', models.BooleanField(default=True)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.agentrun')),
            ],
            options={
                'verbose_name': 'Bước Agent',
                'verbose_name_plural': 'Bước Agent',
                'ordering': ['run', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentstep',
            constraint=models.UniqueConstraint(fields=('run', 'order'), name='uq_agentstep_run_order'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['agent', '-started_at'], name='agents_agen_agent_9db191_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', '-started_at'], name='agents_agen_status_c02e6a_idx'),
        ),
    ]
