# Generated by Django 4.2.23 on 2026-08-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ví dụ: Máy phòng Tuyển dụng — tầng 12', max_length=120, verbose_name='Tên gọi')),
                ('edge_id', models.CharField(blank=True, help_text='Do ứng dụng Edge sinh, gắn khi đăng ký lần đầu', max_length=64, null=True, unique=True, verbose_name='Mã Edge')),
                ('hostname', models.CharField(blank=True, default='', max_length=200, verbose_name='Tên máy')),
                ('app_version', models.CharField(blank=True, default='', max_length=40, verbose_name='Phiên bản Edge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Đăng ký lúc')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần cuối liên lạc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Edge',
                'verbose_name_plural': 'Các Edge',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='EdgeApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120, verbose_name='Ghi chú')),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('prefix', models.CharField(editable=False, help_text='Vài ký tự đầu, chỉ để nhận diện', max_length=16, verbose_name='Đầu khoá')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần cuối sử dụng')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Thu hồi lúc')),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.edge', verbose_name='Edge')),
            ],
            options={
                'verbose_name': 'Khoá API Edge',
                'verbose_name_plural': 'Khoá API Edge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_key', models.CharField(max_length=300)),
                ('payload', models.JSONField(default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('account', models.CharField(blank=True, default='', max_length=200)),
                ('fullname', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('position', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Chờ phân giải'), ('resolved', 'Đã phân giải')], db_index=True, default='pending', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1, help_text='Tăng mỗi lần Edge gửi nội dung khác')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='core.edge')),
            ],
            options={
                'verbose_name': 'Bản ghi nguồn',
                'verbose_name_plural': 'Bản ghi nguồn',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['status', 'last_seen_at'], name='core_source_status_a8b540_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sourcerecord',
            constraint=models.UniqueConstraint(fields=('edge', 'entity_type', 'entity_key'), name='uq_source_record_entity'),
        ),
    ]
