# Generated by Django 4.2.23 on 2026-08-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sourcerecord_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('talent', 'Tuyển dụng'), ('rb', 'Khách hàng')], db_index=True, max_length=20)),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, default='#64748b', max_length=20)),
                ('is_terminal', models.BooleanField(default=False)),
                ('requires_reason', models.BooleanField(default=False)),
                ('sla_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain', 'position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('domain', 'code'), name='uq_workflowstage_domain_code'),
        ),
    ]
