# Generated by Django 4.2.23 on 2026-08-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_refresh_talent_stage_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcerecord',
            name='resolve_attempted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
