# Generated by Django 4.2.23 on 2026-08-31 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_sourcerecord_resolve_attempted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Tên tệp nén')),
                ('storage_key', models.CharField(max_length=500, verbose_name='Đường dẫn lưu trữ')),
                ('storage_backend', models.CharField(default='r2', max_length=32, verbose_name='Nơi lưu trữ')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Dung lượng (bytes)')),
                ('sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='Mã băm SHA-256')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('in_progress', 'Đang sao lưu'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], db_index=True, default='pending', max_length=32, verbose_name='Trạng thái')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Thông báo lỗi')),
                ('trigger_type', models.CharField(choices=[('scheduled', 'Tự động định kỳ (2 lần/ngày)'), ('manual', 'Thủ công (Admin kích hoạt)')], default='manual', max_length=32, verbose_name='Loại kích hoạt')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='Thời gian thực thi (ms)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký sao lưu CSDL',
                'verbose_name_plural': 'Nhật ký sao lưu CSDL',
                'ordering': ['-created_at'],
            },
        ),
    ]
