# Generated by Django 4.2.23 on 2026-09-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_databasebackuplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='data_report',
            field=models.JSONField(blank=True, default=dict, verbose_name='Báo cáo dữ liệu Edge'),
        ),
        migrations.AddField(
            model_name='edge',
            name='data_reported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Báo cáo dữ liệu lúc'),
        ),
    ]
