# Generated by Django 4.2.23 on 2026-08-20 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('talent', 'Talent Radar'), ('rb', 'RB Radar')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bộ lọc đã lưu',
                'verbose_name_plural': 'Bộ lọc đã lưu',
                'ordering': ['-last_used_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='savedview',
            constraint=models.UniqueConstraint(fields=('owner', 'module', 'name'), name='uq_savedview_owner_module_name'),
        ),
    ]
