# Generated by Django 4.2.23 on 2026-08-19 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_alter_document_options_document_file_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('roles', models.CharField(blank=True, default='', help_text='Vai trò tại thời điểm truy cập', max_length=200)),
                ('action', models.CharField(choices=[('view', 'Xem hồ sơ'), ('search', 'Tìm kiếm'), ('list', 'Xem danh sách'), ('download', 'Tải tài liệu'), ('export', 'Xuất dữ liệu')], db_index=True, max_length=20)),
                ('module', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('person_name', models.CharField(blank=True, default='', max_length=200)),
                ('object_type', models.CharField(blank=True, default='', max_length=40)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('cross_domain', models.BooleanField(db_index=True, default=False)),
                ('path', models.CharField(blank=True, default='', max_length=300)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='people.person')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký truy cập',
                'verbose_name_plural': 'Nhật ký truy cập',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['person', '-created_at'], name='accounts_ac_person__39d213_idx'), models.Index(fields=['user', '-created_at'], name='accounts_ac_user_id_c848a8_idx'), models.Index(fields=['cross_domain', '-created_at'], name='accounts_ac_cross_d_e465e7_idx'), models.Index(fields=['action', '-created_at'], name='accounts_ac_action_228ca8_idx')],
            },
        ),
    ]
