# Generated by Django 4.2.23 on 2026-08-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='allowed',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
