# Generated by Django 4.2.23 on 2026-08-29 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_accesslog_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('talent', 'Tuyển dụng'), ('rb', 'Bán lẻ')], db_index=True, max_length=20)),
                ('regions', models.JSONField(blank=True, default=list, help_text='Danh sách tỉnh/thành phụ trách')),
                ('focus_products', models.JSONField(blank=True, default=list, help_text='Mã nhóm sản phẩm ưu tiên (RB)')),
                ('focus_job_families', models.JSONField(blank=True, default=list, help_text='Nhóm vị trí phụ trách (Talent)')),
                ('target_segments', models.JSONField(blank=True, default=list)),
                ('daily_capacity', models.PositiveSmallIntegerField(default=20)),
                ('preferred_channels', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='', help_text='Ngữ cảnh cho AI diễn giải; không đổi điểm số')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ công việc',
                'verbose_name_plural': 'Hồ sơ công việc',
            },
        ),
        migrations.AddConstraint(
            model_name='userworkprofile',
            constraint=models.UniqueConstraint(fields=('user', 'domain'), name='uq_workprofile_user_domain'),
        ),
    ]
