# Generated by Django 4.2.23 on 2026-08-29 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0005_relationship_operational_index'),
        ('accounts', '0003_userworkprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUnlockPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlimited', models.BooleanField(default=False, help_text='Không giới hạn lượt mở khoá liên hệ mỗi ngày')),
                ('custom_daily_quota', models.PositiveIntegerField(blank=True, help_text='Hạn mức riêng; bỏ trống thì dùng mức theo vai trò', null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_policy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hạn mức mở khoá riêng',
                'verbose_name_plural': 'Hạn mức mở khoá riêng',
            },
        ),
        migrations.CreateModel(
            name='ContactUnlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('person_name', models.CharField(blank=True, default='', max_length=200)),
                ('domain', models.CharField(blank=True, default='', help_text='talent hoặc rb', max_length=20)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('unlocked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_unlocks', to='people.person')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký mở khoá liên hệ',
                'verbose_name_plural': 'Nhật ký mở khoá liên hệ',
                'ordering': ['-unlocked_at'],
                'indexes': [models.Index(fields=['user', '-unlocked_at'], name='accounts_co_user_id_a93a60_idx'), models.Index(fields=['person', '-unlocked_at'], name='accounts_co_person__04202a_idx')],
            },
        ),
    ]
