# Generated by Django 4.2.23 on 2026-08-30 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_harden_login_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginpolicy',
            name='login_type',
            field=models.CharField(choices=[('local', 'Tài khoản thường'), ('tntalent', 'Email OTP — TNTalent'), ('msb', 'Email OTP — MSB')], db_index=True, default='local', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailOtpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('resend_api_key_encrypted', models.TextField(blank=True, default='')),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('from_name', models.CharField(blank=True, default='MSB Radar', max_length=100)),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='Mã đăng nhập MSB Radar', max_length=160)),
                ('code_ttl_seconds', models.PositiveIntegerField(default=600)),
                ('resend_cooldown_seconds', models.PositiveIntegerField(default=60)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_otp_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailLoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(choices=[('tntalent', 'TNTalent'), ('msb', 'MSB')], db_index=True, max_length=20)),
                ('sent_to', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_ip', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_login_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'realm', '-created_at'], name='accounts_em_user_id_7b9272_idx')],
            },
        ),
    ]
