# Generated by Django 4.2.23 on 2026-08-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userloginpolicy_login_type_emailotpsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotpsettings',
            name='msb_domains',
            field=models.TextField(blank=True, default='msb.com.vn'),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='tntalent_domains',
            field=models.TextField(blank=True, default='tntalent.vn'),
        ),
    ]
