# Generated by Django 4.2.23 on 2026-08-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_emailotpsettings_msb_domains_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResendInboxEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=80, unique=True)),
                ('sender', models.EmailField(blank=True, default='', max_length=254)),
                ('recipients', models.JSONField(default=list)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('text_body', models.TextField(blank=True, default='')),
                ('html_body', models.TextField(blank=True, default='')),
                ('headers', models.JSONField(default=dict)),
                ('attachments', models.JSONField(default=list)),
                ('received_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at', '-stored_at'],
            },
        ),
        migrations.CreateModel(
            name='ResendWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svix_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('email_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='otp_html_template',
            field=models.TextField(default='<p>Mã đăng nhập {{app_name}} của bạn là:</p><p style="font-size:28px;font-weight:700;letter-spacing:6px">{{code}}</p><p>Mã hết hạn sau {{expires_minutes}} phút. Không chia sẻ mã này cho bất kỳ ai.</p>'),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='webhook_inbound_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='webhook_secret_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
