# Generated by Django 4.2.23 on 2026-08-30 17:29

from django.db import migrations, models


NEW_MSB_TEMPLATE = (
    "<!DOCTYPE html><html lang=\"vi\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Mã xác thực đăng nhập - {{app_name}}</title></head>"
    "<body style=\"margin:0;padding:0;background-color:#F1F5F9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#1E293B;line-height:1.6;\">"
    "<table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"background-color:#F1F5F9;padding:40px 16px;\"><tr><td align=\"center\">"
    "<table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"max-width:580px;background-color:#FFFFFF;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.06);border:1px solid #E2E8F0;\">"
    "<tr><td style=\"background:linear-gradient(135deg, #F59E0B 0%, #FF8A33 50%, #E65C00 100%);padding:28px 36px;text-align:left;\">"
    "<table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"><tr>"
    "<td valign=\"middle\" style=\"width:52px;padding-right:14px;\">"
    "<img src=\"{{app_icon_url}}\" width=\"48\" height=\"48\" alt=\"{{app_name}}\" style=\"display:block;border-radius:12px;border:1.5px solid rgba(255,255,255,0.4);background-color:#FFFFFF;object-fit:contain;box-shadow:0 2px 8px rgba(0,0,0,0.15);\" />"
    "</td>"
    "<td valign=\"middle\">"
    "<div style=\"display:inline-block;background:rgba(255,255,255,0.22);padding:3px 10px;border-radius:20px;font-size:11px;font-weight:700;color:#FFFFFF;letter-spacing:0.5px;margin-bottom:4px;\">XÁC THỰC BẢO MẬT HỆ THỐNG</div>"
    "<h1 style=\"margin:0;color:#FFFFFF;font-size:22px;font-weight:800;letter-spacing:-0.5px;line-height:1.2;\">{{app_name}}</h1>"
    "<p style=\"margin:2px 0 0;color:rgba(255,255,255,0.92);font-size:12.5px;\">Hệ Thống Tìm Kiếm Nhân Tài &amp; Tăng Trưởng Khách Hàng</p>"
    "</td>"
    "</tr></table></td></tr>"
    "<tr><td style=\"padding:32px 36px 28px;\"><h2 style=\"margin:0 0 12px;font-size:19px;font-weight:700;color:#0F172A;\">Mã xác thực đăng nhập (OTP)</h2>"
    "<p style=\"margin:0 0 24px;font-size:14.5px;color:#475569;line-height:1.6;\">Bạn vừa thực hiện yêu cầu đăng nhập an toàn vào hệ thống <strong>{{app_name}}</strong>. Vui lòng sử dụng mã xác thực gồm 6 chữ số dưới đây để tiếp tục:</p>"
    "<table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"margin:0 0 24px;\"><tr><td style=\"background-color:#FFF7ED;border:1.5px dashed #FB923C;border-radius:12px;padding:24px 20px;text-align:center;\">"
    "<div style=\"font-size:12px;font-weight:700;color:#9A3412;text-transform:uppercase;letter-spacing:1px;margin-bottom:6px;\">MÃ XÁC THỰC CỦA BẠN</div>"
    "<div style=\"font-family:'SF Mono',Consolas,'Liberation Mono',Menlo,Courier,monospace;font-size:38px;font-weight:800;color:#EA580C;letter-spacing:10px;line-height:1.2;padding:4px 0;\">{{code}}</div>"
    "<div style=\"font-size:13px;color:#C2410C;font-weight:600;margin-top:8px;\">⏱️ Có hiệu lực trong vòng {{expires_minutes}} phút</div></td></tr></table>"
    "<table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"background-color:#F8FAFC;border:1px solid #E2E8F0;border-radius:10px;padding:16px 18px;margin-bottom:20px;\"><tr><td>"
    "<div style=\"font-size:13px;font-weight:700;color:#334155;margin-bottom:6px;\">🛡️ Lưu ý an ninh quan trọng:</div>"
    "<ul style=\"margin:0;padding-left:18px;font-size:13px;color:#64748B;line-height:1.5;\">"
    "<li style=\"margin-bottom:4px;\">Mã OTP này chỉ có hiệu lực <strong>một lần duy nhất</strong>.</li>"
    "<li style=\"margin-bottom:4px;\"><strong>Tuyệt đối không chia sẻ</strong> mã này với bất kỳ ai, bao gồm cả quản trị viên hay nhân viên hỗ trợ.</li>"
    "<li>Nếu bạn không thực hiện yêu cầu này, vui lòng bỏ qua email hoặc liên hệ ngay với Quản trị viên An ninh.</li></ul></td></tr></table>"
    "</td></tr><tr><td style=\"background-color:#F8FAFC;border-top:1px solid #E2E8F0;padding:20px 36px;text-align:center;\">"
    "<p style=\"margin:0 0 4px;font-size:12.5px;font-weight:600;color:#64748B;\">Email bảo mật tự động từ {{app_name}}</p>"
    "<p style=\"margin:0;font-size:11.5px;color:#94A3B8;\">Ngân hàng TMCP Hàng Hải Việt Nam (MSB) • Đây là email tự động, vui lòng không phản hồi thư này.</p>"
    "</td></tr></table></td></tr></table></body></html>"
)


def upgrade_legacy_template(apps, schema_editor):
    Settings = apps.get_model('accounts', 'EmailOtpSettings')
    for s in Settings.objects.all():
        if not s.otp_html_template or '<p>Mã đăng nhập' in s.otp_html_template or 'background:#0b4f9c' in s.otp_html_template:
            s.otp_html_template = NEW_MSB_TEMPLATE
            s.save(update_fields=['otp_html_template'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_resendinboxemail_resendwebhookevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotpsettings',
            name='otp_html_template',
            field=models.TextField(default=NEW_MSB_TEMPLATE),
        ),
        migrations.AlterField(
            model_name='emailotpsettings',
            name='reply_to',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(upgrade_legacy_template, migrations.RunPython.noop),
    ]
