# Generated by Django 4.2.23 on 2026-08-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_emailotpsettings_otp_html_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillogincode',
            name='realm',
            field=models.CharField(choices=[('local', 'Tài khoản thường'), ('tntalent', 'TNTalent'), ('msb', 'MSB')], db_index=True, max_length=20),
        ),
    ]
