# Generated by Django 4.2.23 on 2026-08-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_emaillogincode_realm'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='externalidentity',
            name='uq_active_external_identity_subject',
        ),
        migrations.RemoveConstraint(
            model_name='externalidentity',
            name='uq_active_external_identity_user_tenant',
        ),
        migrations.RemoveIndex(
            model_name='externalidentity',
            name='accounts_ex_provide_8db87a_idx',
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='provider',
            field=models.CharField(choices=[('microsoft', 'Microsoft Entra ID')], db_index=True, default='microsoft', max_length=30),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='realm',
            field=models.CharField(choices=[('tntalent', 'TNTalent'), ('msb', 'MSB')], db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='externalidentity',
            constraint=models.UniqueConstraint(fields=('provider', 'realm', 'object_id'), name='uq_external_identity_realm_object'),
        ),
    ]
