# Generated by Django 4.2.23 on 2026-08-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_fix_email_otp_icon_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotpsettings',
            name='app_icon',
            field=models.CharField(blank=True, default='⚡', max_length=20),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='app_logo_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='app_tagline',
            field=models.CharField(blank=True, default='Hệ Thống Tìm Kiếm Nhân Tài & Tăng Trưởng Khách Hàng', max_length=255),
        ),
    ]
