# Generated by Django 4.2.23 on 2026-08-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_emailotpsettings_app_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotpsettings',
            name='color_preset',
            field=models.CharField(blank=True, default='amber_gold', max_length=40),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='custom_color',
            field=models.CharField(blank=True, default='#FF8A33', max_length=20),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='items_per_page',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='mask_sensitive_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='min_match_score',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='sound_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='table_density',
            field=models.CharField(blank=True, default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='theme_mode',
            field=models.CharField(blank=True, default='dark', max_length=20),
        ),
    ]
