# Generated by Django 4.2.23 on 2026-08-31 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_emailotpsettings_color_preset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssistantPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác'), ('undisclosed', 'Không muốn cung cấp')], default='', max_length=20)),
                ('preferred_name', models.CharField(blank=True, default='', max_length=80)),
                ('preferred_salutation', models.CharField(blank=True, choices=[('anh', 'Anh'), ('chị', 'Chị'), ('bạn', 'Bạn'), ('', 'Không chỉ định')], default='', max_length=20)),
                ('personalization_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
