# Generated by Django 4.2.23 on 2026-08-31 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_userassistantpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, help_text='Khoá vai trò trong accounts.roles.ALL_ROLES', max_length=32)),
                ('module', models.CharField(help_text='Khoá module trong accounts.roles.MODULE_LABELS', max_length=32)),
                ('allowed', models.BooleanField()),
                ('updated_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phân quyền module theo vai trò',
                'verbose_name_plural': 'Phân quyền module theo vai trò',
                'ordering': ['role', 'module'],
            },
        ),
        migrations.AddConstraint(
            model_name='rolemoduleaccess',
            constraint=models.UniqueConstraint(fields=('role', 'module'), name='uq_role_module_access'),
        ),
    ]
