# Generated by Django 4.2.23 on 2026-08-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rolemoduleaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('view', 'Xem hồ sơ'), ('search', 'Tìm kiếm'), ('list', 'Xem danh sách'), ('download', 'Tải tài liệu'), ('export', 'Xuất dữ liệu'), ('delete', 'Xoá dữ liệu')], db_index=True, max_length=20),
        ),
    ]
