# Generated by Django 4.2.23 on 2026-09-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_accesslog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotpsettings',
            name='meta_keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='meta_robots',
            field=models.CharField(blank=True, default='index, follow', max_length=60),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='og_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='og_image_alt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='og_image_height',
            field=models.PositiveSmallIntegerField(default=630),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='og_image_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='og_image_width',
            field=models.PositiveSmallIntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='og_site_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='og_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='pwa_background_color',
            field=models.CharField(blank=True, default='#0F172A', max_length=20),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='pwa_short_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
