# Generated by Django 4.2.23 on 2026-09-03
from accounts.models import DEFAULT_OTP_HTML_TEMPLATE
from django.db import migrations, models


def upgrade_otp_template_for_outlook(apps, schema_editor):
    Settings = apps.get_model('accounts', 'EmailOtpSettings')
    for s in Settings.objects.all():
        tpl = s.otp_html_template or ""
        # Nếu mẫu hiện tại thiếu bgcolor ở banner hoặc là mẫu mặc định cũ, cập nhật sang mẫu bulletproof
        if not tpl or ("linear-gradient" in tpl and "bgcolor=" not in tpl):
            s.otp_html_template = DEFAULT_OTP_HTML_TEMPLATE
            s.save(update_fields=['otp_html_template'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_emailotpsettings_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotpsettings',
            name='otp_html_template',
            field=models.TextField(default=DEFAULT_OTP_HTML_TEMPLATE),
        ),
        migrations.RunPython(upgrade_otp_template_for_outlook, reverse_code=migrations.RunPython.noop),
    ]
