# Generated by Django 4.2.23 on 2026-09-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_bulletproof_otp_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotpsettings',
            name='gradient_angle',
            field=models.CharField(blank=True, default='135deg', max_length=15),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='gradient_from',
            field=models.CharField(blank=True, default='#FF8A33', max_length=20),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='gradient_to',
            field=models.CharField(blank=True, default='#EA580C', max_length=20),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='gradient_via',
            field=models.CharField(blank=True, default='#F59E0B', max_length=20),
        ),
    ]
