# Generated by Django 4.2.23 on 2026-09-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_emailotpsettings_gradient_angle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotpsettings',
            name='radar_avatar_emoji',
            field=models.CharField(blank=True, default='⚡', max_length=20),
        ),
        migrations.AddField(
            model_name='emailotpsettings',
            name='radar_avatar_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
