# Generated by Django 4.2.23 on 2026-09-03
from accounts.models import DEFAULT_OTP_HTML_TEMPLATE
from django.db import migrations, models


def upgrade_otp_template_to_pure_inline(apps, schema_editor):
    Settings = apps.get_model('accounts', 'EmailOtpSettings')
    for s in Settings.objects.all():
        s.otp_html_template = DEFAULT_OTP_HTML_TEMPLATE
        s.save(update_fields=['otp_html_template'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_emailotpsettings_radar_avatar_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotpsettings',
            name='otp_html_template',
            field=models.TextField(default=DEFAULT_OTP_HTML_TEMPLATE),
        ),
        migrations.RunPython(upgrade_otp_template_to_pure_inline, reverse_code=migrations.RunPython.noop),
    ]
