# Generated by Django 4.2.23 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_update_otp_html_template_inline'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotpsettings',
            name='brand_tag',
            field=models.CharField(blank=True, default='RADAR INTELLIGENCE', max_length=60),
        ),
    ]
