# Generated by Django 4.2.23 on 2026-08-20 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0003_alter_document_options_document_file_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_owner_name', models.CharField(blank=True, default='', max_length=150)),
                ('lead_status', models.CharField(choices=[('cold', 'Chưa tiếp cận'), ('warm', 'Đã tiếp cận'), ('interested', 'Có quan tâm'), ('qualified', 'Đủ điều kiện'), ('converted', 'Đã dùng sản phẩm'), ('dormant', 'Nguội')], db_index=True, default='cold', max_length=20)),
                ('segment', models.CharField(blank=True, choices=[('mass', 'Phổ thông'), ('affluent', 'Khá giả'), ('priority', 'Ưu tiên')], default='', max_length=20)),
                ('occupation', models.CharField(blank=True, default='', max_length=200, verbose_name='Nghề nghiệp')),
                ('employer', models.CharField(blank=True, default='', max_length=200, verbose_name='Nơi làm việc')),
                ('interaction_summary', models.TextField(blank=True, default='')),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, default='', max_length=300)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rb_profile', to='people.person')),
                ('sales_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rb_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ khách hàng cá nhân',
                'verbose_name_plural': 'Hồ sơ khách hàng cá nhân',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RBOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('credit_card', 'Thẻ tín dụng'), ('mortgage', 'Vay mua nhà'), ('auto_loan', 'Vay mua xe'), ('consumer_loan', 'Vay tiêu dùng'), ('savings', 'Tiết kiệm'), ('investment', 'Đầu tư'), ('insurance', 'Bảo hiểm'), ('fx', 'Ngoại tệ / chuyển tiền quốc tế'), ('payroll', 'Tài khoản lương')], db_index=True, max_length=30)),
                ('need', models.CharField(blank=True, default='', help_text='Nói bằng lời của khách, không phải tên sản phẩm', max_length=300, verbose_name='Nhu cầu')),
                ('confidence', models.FloatField(default=0.0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('suggested_action', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('new', 'Mới'), ('accepted', 'Đã nhận'), ('contacting', 'Đang liên hệ'), ('won', 'Thành công'), ('lost', 'Không thành')], db_index=True, default='new', max_length=20)),
                ('assigned_to_name', models.CharField(blank=True, default='', max_length=150)),
                ('close_reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rb_opportunities', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb_opportunities', to='people.person')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rb_opportunities', to='people.signal')),
            ],
            options={
                'verbose_name': 'Cơ hội bán lẻ',
                'verbose_name_plural': 'Cơ hội bán lẻ',
                'ordering': ['-confidence', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('credit_card', 'Thẻ tín dụng'), ('mortgage', 'Vay mua nhà'), ('auto_loan', 'Vay mua xe'), ('consumer_loan', 'Vay tiêu dùng'), ('savings', 'Tiết kiệm'), ('investment', 'Đầu tư'), ('insurance', 'Bảo hiểm'), ('fx', 'Ngoại tệ / chuyển tiền quốc tế'), ('payroll', 'Tài khoản lương')], db_index=True, max_length=30)),
                ('confidence', models.FloatField(default=0.0, help_text='0..1')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, default='', help_text='social, cv, rm_nhap_tay…', max_length=40)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='rb.rbprofile')),
            ],
            options={
                'verbose_name': 'Quan tâm sản phẩm',
                'verbose_name_plural': 'Quan tâm sản phẩm',
                'ordering': ['-confidence', '-observed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rbprofile',
            index=models.Index(fields=['lead_status', '-updated_at'], name='rb_rbprofil_lead_st_338f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='rbopportunity',
            index=models.Index(fields=['status', '-created_at'], name='rb_rbopport_status_627453_idx'),
        ),
        migrations.AddIndex(
            model_name='rbopportunity',
            index=models.Index(fields=['assigned_to', 'status'], name='rb_rbopport_assigne_f1ef68_idx'),
        ),
        migrations.AddConstraint(
            model_name='productinterest',
            constraint=models.UniqueConstraint(fields=('profile', 'product'), name='uq_productinterest_profile_product'),
        ),
    ]
