# Generated by Django 4.2.23 on 2026-08-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbopportunity',
            name='outreach_draft',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rbopportunity',
            name='outreach_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
