# Generated by Django 4.2.23 on 2026-08-22 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rb', '0002_rbopportunity_outreach_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbopportunity',
            name='next_action_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rbopportunity',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rbopportunity',
            name='priority',
            field=models.CharField(choices=[('low', 'Thấp'), ('normal', 'Bình thường'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], db_index=True, default='normal', max_length=10),
        ),
        migrations.CreateModel(
            name='RBOpportunityStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='rb.rbopportunity')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['opportunity', '-created_at'], name='rb_rbopport_opportu_523caa_idx')],
            },
        ),
    ]
