# Generated by Django 4.2.23 on 2026-08-29 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0005_relationship_operational_index'),
        ('rb', '0004_opportunity_work_inbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductValueConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('credit_card', 'Thẻ tín dụng'), ('mortgage', 'Vay mua nhà'), ('auto_loan', 'Vay mua xe'), ('consumer_loan', 'Vay tiêu dùng'), ('savings', 'Tiết kiệm'), ('investment', 'Đầu tư'), ('insurance', 'Bảo hiểm'), ('fx', 'Ngoại tệ / chuyển tiền quốc tế'), ('payroll', 'Tài khoản lương')], max_length=30, unique=True)),
                ('value_band', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('very_high', 'Rất cao')], default='medium', max_length=20)),
                ('value_weight', models.FloatField(default=0.0, help_text='0 = chưa có số thật, dùng thang định tính')),
                ('strategic_weight', models.FloatField(default=1.0, help_text='Hệ số nhân, 1.0 = trung tính')),
                ('business_priority', models.IntegerField(default=0, help_text='Thứ tự hiển thị khi bằng điểm')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình giá trị sản phẩm',
                'verbose_name_plural': 'Cấu hình giá trị sản phẩm',
                'ordering': ['-business_priority', 'product'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('call', 'Gọi điện'), ('sms', 'Tin nhắn'), ('email', 'Email'), ('zalo', 'Zalo'), ('meeting', 'Gặp trực tiếp'), ('other', 'Khác')], default='call', max_length=20)),
                ('action', models.CharField(blank=True, choices=[('CALL_NOW', 'Gọi ngay'), ('SEND_MESSAGE', 'Nhắn tin'), ('ASK_FOR_INFORMATION', 'Hỏi thêm thông tin'), ('FOLLOW_UP', 'Theo dõi tiếp'), ('WAIT', 'Chờ'), ('REACTIVATE', 'Kích hoạt lại'), ('INVITE_MEETING', 'Mời gặp'), ('CLOSE', 'Đóng')], default='', max_length=30)),
                ('outcome', models.CharField(choices=[('NO_RESPONSE', 'Không phản hồi'), ('READ', 'Đã đọc'), ('REPLIED', 'Có trả lời'), ('INTERESTED', 'Quan tâm'), ('MAYBE_LATER', 'Để sau'), ('NOT_INTERESTED', 'Không quan tâm'), ('WRONG_PRODUCT', 'Sai sản phẩm'), ('ALREADY_USING', 'Đang dùng rồi'), ('NEED_CONSULTATION', 'Cần tư vấn thêm'), ('MEETING_BOOKED', 'Đã hẹn gặp'), ('CONVERTED', 'Đã chốt')], db_index=True, max_length=30)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('response_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='rb.rbopportunity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb_outcomes', to='people.person')),
            ],
            options={
                'verbose_name': 'Kết quả tiếp cận',
                'verbose_name_plural': 'Kết quả tiếp cận',
                'ordering': ['-response_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunitySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('credit_card', 'Thẻ tín dụng'), ('mortgage', 'Vay mua nhà'), ('auto_loan', 'Vay mua xe'), ('consumer_loan', 'Vay tiêu dùng'), ('savings', 'Tiết kiệm'), ('investment', 'Đầu tư'), ('insurance', 'Bảo hiểm'), ('fx', 'Ngoại tệ / chuyển tiền quốc tế'), ('payroll', 'Tài khoản lương')], db_index=True, max_length=30)),
                ('need_summary', models.CharField(blank=True, default='', help_text='Nói bằng lời của khách, không phải tên sản phẩm', max_length=300, verbose_name='Nhu cầu')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('fit_score', models.FloatField(default=0.0)),
                ('need_score', models.FloatField(default=0.0)),
                ('timing_score', models.FloatField(default=0.0)),
                ('reachability_score', models.FloatField(default=0.0)),
                ('value_score', models.FloatField(default=0.0)),
                ('priority_score', models.FloatField(db_index=True, default=0.0)),
                ('confidence', models.FloatField(default=0.0, help_text='0..1')),
                ('recommended_action', models.CharField(choices=[('CALL_NOW', 'Gọi ngay'), ('SEND_MESSAGE', 'Nhắn tin'), ('ASK_FOR_INFORMATION', 'Hỏi thêm thông tin'), ('FOLLOW_UP', 'Theo dõi tiếp'), ('WAIT', 'Chờ'), ('REACTIVATE', 'Kích hoạt lại'), ('INVITE_MEETING', 'Mời gặp'), ('CLOSE', 'Đóng')], default='FOLLOW_UP', max_length=30)),
                ('reasoning_summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('reviewed', 'Đã xem'), ('accepted', 'Đã nhận'), ('snoozed', 'Để sau'), ('dismissed', 'Bỏ qua'), ('expired', 'Hết hạn'), ('converted_to_opportunity', 'Đã thành cơ hội')], db_index=True, default='new', max_length=30)),
                ('dismiss_reason', models.CharField(blank=True, default='', max_length=300)),
                ('snoozed_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('converted_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_suggestions', to='rb.rbopportunity')),
                ('owner_suggestion', models.ForeignKey(blank=True, help_text='RM được gợi ý phụ trách; chưa phải người nhận', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rb_suggestions', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb_suggestions', to='people.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_signals', models.ManyToManyField(blank=True, related_name='rb_suggestions', to='people.signal')),
            ],
            options={
                'verbose_name': 'Đề xuất cơ hội',
                'verbose_name_plural': 'Đề xuất cơ hội',
                'ordering': ['-priority_score', '-created_at'],
                'indexes': [models.Index(fields=['status', '-priority_score'], name='rb_opportun_status_a2756a_idx'), models.Index(fields=['owner_suggestion', 'status', '-priority_score'], name='rb_sugg_owner_status_idx'), models.Index(fields=['person', '-created_at'], name='rb_opportun_person__fed206_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='opportunitysuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('new', 'reviewed', 'snoozed'))), fields=('person', 'product'), name='uq_rb_active_suggestion_person_product'),
        ),
        migrations.AddIndex(
            model_name='opportunityoutcome',
            index=models.Index(fields=['opportunity', '-response_at'], name='rb_opportun_opportu_4813c5_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityoutcome',
            index=models.Index(fields=['outcome', '-response_at'], name='rb_opportun_outcome_c38f5c_idx'),
        ),
    ]
