# Generated by Django 4.2.23 on 2026-09-17 01:24

from django.db import migrations, models

# Chỉ mục biểu thức GIN cho full-text trên text đã bỏ dấu — cùng cách
# `talent/migrations/0007` làm cho CVChunk. SQLite (dev/test) bỏ qua an toàn.
_FTS = ("rb_pec_text_norm_fts", "rb_prospectevidencechunk", "text_norm")


def create_fts_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    name, table, column = _FTS
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"CREATE INDEX IF NOT EXISTS {name} ON {table} "
                       f"USING GIN (to_tsvector('simple', {column}))")


def drop_fts_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"DROP INDEX IF EXISTS {_FTS[0]}")
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_document_intelligence_feed_index'),
        ('rb', '0006_seed_product_value_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectEvidenceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=80, unique=True)),
                ('source', models.CharField(db_index=True, max_length=20)),
                ('text', models.TextField()),
                ('text_norm', models.TextField(blank=True, default='')),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=120)),
                ('embedding_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_evidence_chunks', to='people.person')),
            ],
            options={
                'verbose_name': 'Bằng chứng khách hàng (chỉ mục)',
                'verbose_name_plural': 'Bằng chứng khách hàng (chỉ mục)',
                'indexes': [models.Index(fields=['person', '-observed_at'], name='rb_pec_person_observed_idx')],
            },
        ),
        migrations.RunPython(create_fts_index, drop_fts_index),
    ]
